In [1]:
import pandas as pd
import collections
import numpy as np

from sklearn.metrics import confusion_matrix, classification_report, precision_score
from sklearn.decomposition import PCA

In [2]:
def QDA(Xapp, zapp, mprior, df_exp, Sprior, df_cov):
    n, p, K =  Xapp.shape[0], Xapp.shape[1], zapp.shape[1]
    pi = np.zeros(K)
    mu = np.zeros((K, p))
    B = np.zeros((n, p, p))
    Sig = np.zeros((p, p, K))
    
    pi = np.mean(zapp, axis=0)
    for j in range(K):
        mu[j, :] = (sum(zapp[i, j] * Xapp[i, :] for i in range(n)) 
                    + df_exp * mprior[j, :]) / (sum(zapp[:, j]) + df_exp)
        
        for i in range(n):
            temp = (Xapp[i, :] - mprior[j, :]).reshape((p, -1))
            B[i, :, :] = temp @ temp.T
        
        Sig[:, :, j] = (sum((zapp[i, j] * B[i, :, :]) for i in range(n)) + 
                        df_exp * (mu[j, :] - mprior[j, :]) @ (mu[j, :] - mprior[j, :]).T + 
                        Sprior[:, :, j]) / (sum(zapp[:, j]) + df_cov + p + 2)
        
    return pi, mu, Sig

In [3]:
def evaluation(Xtst, pi, mu, Sig):
    n, p, K = Xtst.shape[0], Xtst.shape[1], len(pi)
    prob = np.zeros((n, K))
    pred = np.zeros(n)
    
    f = lambda x, mu, Sig: (2 * np.pi)**(-n/2) * np.linalg.det(Sig)**(-1/2) * np.exp((-1/2) * (x - mu).T
                                                                                     @ np.linalg.pinv(Sig)
                                                                                     @ (x - mu))
   
    for j in range(K):
        for i in range(n):
            total = sum(pi[k] * f(Xtst[i, :], mu[k, :], Sig[:, :, k]) for k in range(K))
            prob[i, j] = pi[j] * f(Xtst[i, :], mu[j, :], Sig[:, :, j]) / total
    
    pred = np.argmax(prob, axis=1)
    
    return prob, pred

In [4]:
def data_processing(file_url, n_components_pca=None, cut_off=0.9):
    data = pd.read_csv(file_url, header=0)
    data = data.to_numpy()
    
    if n_components_pca is not None:
        data_y = data[:, -1]
        data_X = data[:, :-1]
        pca = PCA(n_components=n_components_pca)
        data_X = pca.fit_transform(data_X)
        data = np.hstack((data_X, data_y.reshape((-1,1))))
    
    classes = sorted(collections.Counter(list(data[:, -1])).keys())
    classes_with_index = {}
    
    K = len(classes)
    n, p = data.shape[0], data.shape[1] - 1
    for i_class in range(K):
        classes_with_index[i_class] = classes[i_class]
        data[data[:, -1] == classes[i_class], -1] = i_class
    print("Ours classes are enumerated as bellow : \n", classes_with_index)
    
    cut_off = int(cut_off*data.shape[0])
    if cut_off > data.shape[0]:
        raise IndexError("list index out of range")
    else:
        Xapp = data[0:cut_off, :-1]
        Xtst = data[cut_off:, :-1]

        Zapp = np.zeros((cut_off, K))
        Ztst = np.zeros((n - cut_off, K))

        for i in range(cut_off):
            Zapp[i, int(data[i, -1])] = 1
        for i in range(cut_off, n):
            Ztst[i - cut_off, int(data[i, -1])] = 1
    
    mprior = np.zeros((K, p))
    Sprior = np.zeros((p, p, K))
    for j in range(K):
        temp = data[data[:, -1] == j, :-1]
        temp = temp.astype(float)
        mprior[j, :] = temp.mean(axis = 0)
        Sprior[:, :, j] = np.cov(temp, rowvar=False)
    return Xapp, Zapp, Xtst, Ztst, mprior, Sprior

In [5]:
Xapp_opt, Zapp_opt, Xtst_opt, Ztst_opt, mprior_opt, Sprior_opt = data_processing("dataset/optdigits.csv",
                                                                                 n_components_pca=48)

df_exp_opt = 10
df_cov_opt = 300

pi_opt, mu_opt, Sig_opt = QDA(Xapp_opt, Zapp_opt, mprior_opt, df_exp_opt, Sprior_opt, df_cov_opt)
prob_opt, pred_opt = evaluation(Xtst_opt, pi_opt, mu_opt, Sig_opt)

print('\n\n')
print(confusion_matrix(np.argmax(Ztst_opt, axis=1), pred_opt))
print('\n\n')
print(classification_report(np.argmax(Ztst_opt, axis=1), pred_opt))
print('\n\n')
print(precision_score(np.argmax(Ztst_opt, axis=1), pred_opt, average='weighted'))

Ours classes are enumerated as bellow : 
 {0: 0.0, 1: 1.0, 2: 2.0, 3: 3.0, 4: 4.0, 5: 5.0, 6: 6.0, 7: 7.0, 8: 8.0, 9: 9.0}


/home/huydung/miniconda3/envs/aos1/lib/python3.7/site-packages/ipykernel_launcher.py:13: RuntimeWarning: invalid value encountered in double_scalars
  del sys.path[0]





[[55  0  0  0  0  0  0  0  0  0]
 [ 0 56  0  0  0  0  0  0  2  0]
 [ 0  0 54  0  0  0  0  0  0  0]
 [ 0  0  0 51  0  1  0  0  5  0]
 [ 0  0  0  0 56  0  0  0  3  0]
 [ 0  0  0  0  0 55  0  0  0  1]
 [ 0  0  0  0  0  0 57  0  0  0]
 [ 0  0  0  0  0  0  0 56  1  0]
 [ 0  0  0  0  0  0  0  0 53  0]
 [ 1  0  0  0  0  1  0  1  1 52]]



              precision    recall  f1-score   support

           0       0.98      1.00      0.99        55
           1       1.00      0.97      0.98        58
           2       1.00      1.00      1.00        54
           3       1.00      0.89      0.94        57
           4       1.00      0.95      0.97        59
           5       0.96      0.98      0.97        56
           6       1.00      1.00      1.00        57
           7       0.98      0.98      0.98        57
           8       0.82      1.00      0.90        53
           9       0.98      0.93      0.95        56

    accuracy                           0.97       562
   macro avg 

In [6]:
Xapp_pag, Zapp_pag, Xtst_pag, Ztst_pag, mprior_pag, Sprior_pag = data_processing("dataset/page-blocks.csv")

df_exp_pag = 10
df_cov_pag = 300

pi_pag, mu_pag, Sig_pag = QDA(Xapp_pag, Zapp_pag, mprior_pag, df_exp_pag, Sprior_pag, df_cov_pag)
prob_pag, pred_pag = evaluation(Xtst_pag, pi_pag, mu_pag, Sig_pag)

print('\n\n')
print(confusion_matrix(np.argmax(Ztst_pag, axis=1), pred_pag))
print('\n\n')
print(classification_report(np.argmax(Ztst_pag, axis=1), pred_pag))
print('\n\n')
print(precision_score(np.argmax(Ztst_pag, axis=1), pred_pag, average='weighted'))

Ours classes are enumerated as bellow : 
 {0: 1.0, 1: 2.0, 2: 3.0, 3: 4.0, 4: 5.0}


/home/huydung/miniconda3/envs/aos1/lib/python3.7/site-packages/ipykernel_launcher.py:13: RuntimeWarning: invalid value encountered in double_scalars
  del sys.path[0]





[[428   5   0   2  15]
 [ 13  59   0   0   0]
 [  2   0   2   0   0]
 [  2   0   0  15   0]
 [  2   0   0   0   3]]



              precision    recall  f1-score   support

           0       0.96      0.95      0.95       450
           1       0.92      0.82      0.87        72
           2       1.00      0.50      0.67         4
           3       0.88      0.88      0.88        17
           4       0.17      0.60      0.26         5

    accuracy                           0.93       548
   macro avg       0.79      0.75      0.73       548
weighted avg       0.94      0.93      0.93       548




0.9435781323992881


In [7]:
Xapp_sat, Zapp_sat, Xtst_sat, Ztst_sat, mprior_sat, Sprior_sat = data_processing("dataset/satimage.csv")

df_exp_sat = 10
df_cov_sat = 300

pi_sat, mu_sat, Sig_sat = QDA(Xapp_sat, Zapp_sat, mprior_sat, df_exp_sat, Sprior_sat, df_cov_sat)
prob_sat, pred_sat = evaluation(Xtst_sat, pi_sat, mu_sat, Sig_sat)

print('\n\n')
print(confusion_matrix(np.argmax(Ztst_sat, axis=1), pred_sat))
print('\n\n')
print(classification_report(np.argmax(Ztst_sat, axis=1), pred_sat))
print('\n\n')
print(precision_score(np.argmax(Ztst_sat, axis=1), pred_sat, average='weighted'))

Ours classes are enumerated as bellow : 
 {0: 1.0, 1: 2.0, 2: 3.0, 3: 4.0, 4: 5.0, 5: 7.0}



[[164   0   1   0   3   0]
 [  0  63   0   0   1   0]
 [  1   2 134   1   1   1]
 [  1   3  20  12   5  28]
 [  1   2   0   0  64   2]
 [  0   3   5   6   5 114]]



              precision    recall  f1-score   support

           0       0.98      0.98      0.98       168
           1       0.86      0.98      0.92        64
           2       0.84      0.96      0.89       140
           3       0.63      0.17      0.27        69
           4       0.81      0.93      0.86        69
           5       0.79      0.86      0.82       133

    accuracy                           0.86       643
   macro avg       0.82      0.81      0.79       643
weighted avg       0.84      0.86      0.83       643




0.8421588047083794


In [8]:
Xapp_seg, Zapp_seg, Xtst_seg, Ztst_seg, mprior_seg, Sprior_seg = data_processing("dataset/segment.csv",
                                                                                n_components_pca=17)

df_exp_seg = 10
df_cov_seg = 300

pi_seg, mu_seg, Sig_seg = QDA(Xapp_seg, Zapp_seg, mprior_seg, df_exp_seg, Sprior_seg, df_cov_seg)
prob_seg, pred_seg = evaluation(Xtst_seg, pi_seg, mu_seg, Sig_seg)

print('\n\n')
print(confusion_matrix(np.argmax(Ztst_seg, axis=1), pred_seg))
print('\n\n')
print(classification_report(np.argmax(Ztst_seg, axis=1), pred_seg))
print('\n\n')
print(precision_score(np.argmax(Ztst_seg, axis=1), pred_seg, average='weighted'))

Ours classes are enumerated as bellow : 
 {0: 'brickface', 1: 'cement', 2: 'foliage', 3: 'grass', 4: 'path', 5: 'sky', 6: 'window'}



[[25  1  0  0  0  0  2]
 [ 0 37  0  0  0  0  2]
 [ 0  0 16  0  0  0 12]
 [ 0  0  0 29  0  0  0]
 [ 0  4  0  0 31  0  0]
 [ 0  0  0  0  0 38  0]
 [ 0 11  1  0  0  0 22]]



              precision    recall  f1-score   support

           0       1.00      0.89      0.94        28
           1       0.70      0.95      0.80        39
           2       0.94      0.57      0.71        28
           3       1.00      1.00      1.00        29
           4       1.00      0.89      0.94        35
           5       1.00      1.00      1.00        38
           6       0.58      0.65      0.61        34

    accuracy                           0.86       231
   macro avg       0.89      0.85      0.86       231
weighted avg       0.88      0.86      0.86       231




0.879928860593619


In [9]:
# 0.9766310415063318 1;p+20 ll
# 0.9758926103474012 10;p+20
# 0.9671482548426473 10;p+300 
# v reprensent the least informative -> v high -> cov lower -> more "confident" ????
# high df_cov -> Sig =~~ sampling covariance matrix (in this case Sprior)